baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target
name = "aws-s3-cloud-demo-hugo-website"
URL = "s3://cloud-demo-hugo-website/?region=us-east-1"
